# Site wide configuration

title: Ali Shehryar
locale: en_US
description: Stoic | Artificer | Life Long Learner
logo: site-logo.png
search: true
url: http://localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Ali Shehryar
  avatar: bio-photo.jpg
  email: you@email.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: https://github.com/sshehryar
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: https://pk.linkedin.com/in/ashehryar
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
